stages:
  - lint
  - build
  - tests
  
lint-job:
    stage: lint
    before_script:
      - echo "Download some packages..."
      - apt-get update -y
      - apt-get install -y python3-pip
      - python3 -m pip install cpplint
      - echo "Download complete."
    script:
        - echo "Linting the code..."
        - python3 -m cpplint --quiet --recursive *
        - echo "Linting complete."

build-job:
  stage: build
  before_script:
      - echo "Download some packages..."
      - apt-get update -y
      - apt-get install -y make gcc flex bison
      - echo "Download complete."
  script:
    - echo "Compiling the code..."
    - make
    - echo "Compile complete."

tests-job:
  stage: tests
  before_script:
      - echo "Download some packages..."
      - apt-get update -y
      - apt-get install -y make gcc spim flex bison
      - export COLORIZE=0
      - echo "Download complete."
  script:
    - echo "Launching tests..."
    - sh tests.sh
    - echo "Tests finished."
  only:
    - main