stages:
  - lint
  - build
  - test
  
lint-job:
    stage: lint
    before_script:
      - echo "Download some packages..."
      - apt-get update -y
      - apt-get install -y python3-pip
      - python3 -m pip install cpplint
      - echo "Download complete."
    script:
        - echo "Linting the code..."
        - python3 -m cpplint --quiet --recursive *
        - echo "Linting complete."

build-job:
  stage: build
  before_script:
      - echo "Download some packages..."
      - apt-get update -y
      - apt-get install -y make gcc flex bison
      - echo "Download complete."
  script:
    - echo "Compiling the code..."
    - make
    - echo "Compile complete."

tests-job:
  stage: test
  before_script:
      - echo "Download some packages..."
      - apt-get update -y
      - apt-get install -y make gcc flex bison openjdk-17-jdk
      - java -jar tests/mars.jar nc tests/1-base/1-mars/in.asm
      - export COLORIZE=0
      - echo "Download complete."
  script:
    - echo "Launching test..."
    - sh tests.sh
    - echo "Test finished"
  only:
    - main
